package verkehrschaos;

/**
* verkehrschaos/ELocationNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Freitag, 17. April 2015 12:12 Uhr MESZ
*/

public final class ELocationNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public verkehrschaos.ELocationNotFound value = null;

  public ELocationNotFoundHolder ()
  {
  }

  public ELocationNotFoundHolder (verkehrschaos.ELocationNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = verkehrschaos.ELocationNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    verkehrschaos.ELocationNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return verkehrschaos.ELocationNotFoundHelper.type ();
  }

}
