package verkehrschaos;


/**
* verkehrschaos/ETruckCompanyUnknown.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Freitag, 17. April 2015 12:12 Uhr MESZ
*/

public final class ETruckCompanyUnknown extends org.omg.CORBA.UserException
{
  public String msg = null;

  public ETruckCompanyUnknown ()
  {
    super(ETruckCompanyUnknownHelper.id());
  } // ctor

  public ETruckCompanyUnknown (String _msg)
  {
    super(ETruckCompanyUnknownHelper.id());
    msg = _msg;
  } // ctor


  public ETruckCompanyUnknown (String $reason, String _msg)
  {
    super(ETruckCompanyUnknownHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class ETruckCompanyUnknown
