package verkehrschaos;

/**
* verkehrschaos/ETruckUnknownHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Freitag, 17. April 2015 12:12 Uhr MESZ
*/

public final class ETruckUnknownHolder implements org.omg.CORBA.portable.Streamable
{
  public verkehrschaos.ETruckUnknown value = null;

  public ETruckUnknownHolder ()
  {
  }

  public ETruckUnknownHolder (verkehrschaos.ETruckUnknown initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = verkehrschaos.ETruckUnknownHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    verkehrschaos.ETruckUnknownHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return verkehrschaos.ETruckUnknownHelper.type ();
  }

}
