package verkehrschaos;

/**
* verkehrschaos/TruckCompanyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Freitag, 17. April 2015 12:12 Uhr MESZ
*/

public final class TruckCompanyHolder implements org.omg.CORBA.portable.Streamable
{
  public verkehrschaos.TruckCompany value = null;

  public TruckCompanyHolder ()
  {
  }

  public TruckCompanyHolder (verkehrschaos.TruckCompany initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = verkehrschaos.TruckCompanyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    verkehrschaos.TruckCompanyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return verkehrschaos.TruckCompanyHelper.type ();
  }

}
