package verkehrschaos;


/**
* verkehrschaos/TTruckListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Freitag, 17. April 2015 12:12 Uhr MESZ
*/

public final class TTruckListHolder implements org.omg.CORBA.portable.Streamable
{
  public verkehrschaos.Truck value[] = null;

  public TTruckListHolder ()
  {
  }

  public TTruckListHolder (verkehrschaos.Truck[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = verkehrschaos.TTruckListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    verkehrschaos.TTruckListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return verkehrschaos.TTruckListHelper.type ();
  }

}
